# Generated by Django 4.2.4 on 2023-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="crew",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name"), name="unique_crew"
            ),
        ),
    ]
